apiVersion: v1
kind: Namespace
metadata:
  name: demo-agic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: demo-agic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo:1.0.0
          args:
            - "-text=hello-from-agic"
          ports:
            - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: demo-agic
spec:
  selector:
    app: echo
  ports:
    - name: http
      port: 80
      targetPort: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo
  namespace: demo-agic
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: appgw-ssl-cert
spec:
  ingressClassName: azure-application-gateway
  rules:
    - host: netl1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo
                port:
                  number: 80
